### ISSUE TITLE
Can you explain getAbsoluteScale function?

### ISSUE THREAD

**Issue by chaowu2009** [avisingh599/mono-vo#10]
scale = getAbsoluteScale(numFrame, 0, t.at<double>(2));
The result is always zero. 
I don't know how this function is computed. Any reference? Thanks.

**Comment by chaowu2009** [comment]
The current calib.txt file have four lines. Each line has 12 parameters and fit into the extrinsic parameters as following. And nothing more there. 
P0: 7.188560000000e+02 0.000000000000e+00 6.071928000000e+02 0.000000000000e+00 0.000000000000e+00 7.188560000000e+02 1.852157000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
P1: 7.188560000000e+02 0.000000000000e+00 6.071928000000e+02 -3.861448000000e+02 0.000000000000e+00 7.188560000000e+02 1.852157000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
P2: 7.188560000000e+02 0.000000000000e+00 6.071928000000e+02 4.538225000000e+01 0.000000000000e+00 7.188560000000e+02 1.852157000000e+02 -1.130887000000e-01 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 3.779761000000e-03
P3: 7.188560000000e+02 0.000000000000e+00 6.071928000000e+02 -3.372877000000e+02 0.000000000000e+00 7.188560000000e+02 1.852157000000e+02 2.369057000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 4.915215000000e-03

**Comment by avisingh599** [comment]
While doing Visual Odometry from a single camera, it is not possible to obtain the exact scale of the translation from one frame to the next. That is, I cannot distinguish between (0.1, 0.1, 0.1) and (1, 1, 1). So, my solution is correct only up to a constant. the getAbsoluteScale method read this scale constant (obtained from some other sensor like a speedometer).

Every row of the file (00.txt) has 12 elements. These 12 elements correspond to elements of a 3x4 matrix (written down row-wise). This 3x4 matrix is basically the horizontal concatenation of matrix R ( 3x3 rotation matrix) and translation vector t (3x1 vector).

**Comment by kozuch** [comment]
@avisingh599 

Do you offer the 00.txt file for download or do we need to generate it ourselves using LIBVISO with stereo input to get the translation matrix?

**Comment by bharatik-IISc** [comment]
@kozuch You can find it in the KITTI dataset after extracting the data_odometry_poses.zip file
