### ISSUE TITLE
where to download "00.txt"

### ISSUE THREAD

**Issue by amiltonwong** [avisingh599/mono-vo#6]
Hi, @avisingh599 ,

Where could i download "00.txt" for absolute scale? I couldn't find it in KITTI website.

**Comment by amiltonwong** [comment]
I found it

**Comment by kozuch** [comment]
@amiltonwong 

Where did you find the file? From the other issue #10 from third comment it looks like Avi ran the dataset through the LIBVISO library and saved output to a file. LIBVISO uses stereo input and outputs exactly the translation matrix (3x4) Avi is talking about... Looks like if the fila is not available for download then one has to generate it using LIBVISO...

**Comment by amiltonwong** [comment]
@kozuch ,
00.txt is the ground truth for sequence 00, it locates at “[KITTI_VO_dataset]/poses/00.txt”  after you download the KITTI VO dataset

**Comment by kozuch** [comment]
@amiltonwong 

Thanks, you saved my day! I have been working with the stereo KITTI dataset for a while and have not realized the odometry dataset is another one...

**Comment by Shivani1796** [comment]
@kozuch 

Hey, i am doing the same with my own created dataset as you told that LIBVISO generate the translation matrix of 3x4 which can be used for pose ffile , can you help me that how to generate this by LIBVISO ? 
Thanks
