### ISSUE TITLE
My map is too small

### ISSUE THREAD

**Issue by jack3979** [avisingh599/mono-vo#7]
Hi, your project is very nice. But after i run your code with Kitti dataset sequence 11. I have an issue:
![screenshot from 2016-06-26 22 38 19](https://cloud.githubusercontent.com/assets/20153615/16363244/cc6ab164-3bee-11e6-854f-1b7a7245ce49.png)
My map is too small :( . Can you give me some advice to solve this problem?
Thanks.

**Comment by avisingh599** [comment]
Hmm. You did not face this issue with any of the other sequences?

**Comment by jack3979** [comment]
I have been tested on 3 sequences (00, 11, 12). All of them are the same problem. I think this issue rises from  getAbsoluteScale function. I try to find the groundtruth in your report on the internet but no result. Can you give it to me, i will test again.

**Comment by avisingh599** [comment]
This is a fairly old project for me, and I don't have any data with me anymore. There's probably an issue in the way you are printing the calculated trajectory. Do you use `t_f.at<double>(0)` and `t_f.at<double>(2)`?

**Comment by jack3979** [comment]
Yes, i have uncomment this line
`myfile << t_f.at<double>(0) << " " << t_f.at<double>(1) << " " << t_f.at<double>(2) << endl;`
to store calculated trajectory in txt file.

**Comment by avisingh599** [comment]
Try printing out the values returned by the `getAbsoluteScale` function. They should be in the ~1m range while the vehicle is moving. If they aren't, then there is something incorrect there. 

It's surprising that this is happening, it worked on my system as far as I can remember.

**Comment by jack3979** [comment]
This is my log:

```
Scale is 0.179389
125
Scale is 0.180999
126
Scale is 0.178401
Number of tracked features reduced to 1855
trigerring redection
127
Scale is 0.179787
128
Scale is 0.179718
129
Scale is 0.179596
130
Scale is 0.179492
131
Scale is 0.181502
132
Scale is 0.179042
133
Scale is 0.179856
```

:(

**Comment by avisingh599** [comment]
So there's something definitely wrong here. Check if you have filled in this value correctly:
`ifstream myfile ("/home/avisingh/Datasets/KITTI_VO/00.txt");`

**Comment by avisingh599** [comment]
Also, did you pay attention to this
`// WARNING: different sequences in the KITTI VO dataset have different intrinsic/extrinsic parameters`
  `double focal = 718.8560;`
  `cv::Point2d pp(607.1928, 185.2157);`

**Comment by jack3979** [comment]
in `ifstream myfile ("/home/avisingh/Datasets/KITTI_VO/00.txt");` i inserted times.txt of my test sequence.
and parameters `double focal = 718.8560; cv::Point2d pp(607.1928, 185.2157);` I didn't find the parameters for my test sequence, so i didn't change it. Can you show me how to find it?

**Comment by avisingh599** [comment]
There's your issue. You must insert the ground truth file there, since it extracts the scale information from the ground truth (I mention this in the blog post and the report).

**Comment by jack3979** [comment]
Sorry for my mistake, I will correct it and report again. Many thanks for your support :)
One more, Nister 's 5point algorithm is too difficult to understand :D

**Comment by avisingh599** [comment]
Closing this now, you can open it if you're unable to fix it.

**Comment by jack3979** [comment]
Hi,
I think with different sequence I have to change algorithm of `getAbsoluteScale` function. Call you tell me the ideal how to change it? My ground truth sample is following:
[11.txt](https://github.com/avisingh599/mono-vo/files/334840/11.txt)

While i change `t_f = t_f + 0.78*(R_f*t);` and the result:
![screenshot from 2016-06-27 17 02 37](https://cloud.githubusercontent.com/assets/20153615/16376127/05d5dd8a-3c89-11e6-8132-34f4d981ad09.png)

thanks.

**Comment by avisingh599** [comment]
No, you don't have to change it. You must provide the ground truth files in the KITTI format (12 columns), and it will work.

**Comment by jack3979** [comment]
Yes, I found an ground truth file on KITTI 's website, and it worked charm :100: 
But i have another question, with ground truth file below, how to plot ground truth and trajectory?
My ground truth file:
[00.txt](https://github.com/avisingh599/mono-vo/files/336300/00.txt)
My gnuplot script is below, but it not work correctly :( .

> set term postscript eps enhanced color
> set output "11.eps"
> set size ratio -1
> set xrange [-321:313]
> set yrange [-28:606]
> set xlabel "x [m]"
> set ylabel "z [m]"
> plot "11.txt" using 1:2 lc rgb "#FF0000" title 'Ground Truth' w lines,"11.txt" using 3:4 lc rgb "#0000FF" title 'Visual Odometry' w lines,"< head -1 11.txt" using 1:2 lc rgb "#000000" pt 4 ps 1 lw 2 title 'Sequence Start' w points

Thanks.

**Comment by jack3979** [comment]
Please answer my questions :(

**Comment by avisingh599** [comment]
I do not use GNU plot, cannot help you there. However, I don't think you should use the first two columns for the x, y values. It should more like 1st column, 5th column, 9th column or something like that for x,y,z

**Comment by jack3979** [comment]
:( how to you plot your trajectory in your report? Please give me some advice?

**Comment by avisingh599** [comment]
I used MATLAB to plot it.

**Comment by jack3979** [comment]
Yes, can you give me the matlab file? With orginal ground truth file i have no ideal to plot it, i try to use gnuplot but failed :(

**Comment by jack3979** [comment]
Help me, please :(
