### ISSUE TITLE
The error during the step of : make

### ISSUE THREAD

**Issue by zyffse** [avisingh599/mono-vo#9]
Thank your for your excellent work, I met some error when I tried to learn your code. Please help me .

leon@leon-Prime-Series:~/mono-vo/build$ make
Scanning dependencies of target vo
[100%] Building CXX object CMakeFiles/vo.dir/src/visodo.cpp.o
/home/leon/mono-vo/src/visodo.cpp: In function ‘int main(int, char**)’:
/home/leon/mono-vo/src/visodo.cpp:192:48: error: ‘CV_RGB’ was not declared in this scope
     circle(traj, Point(x, y) ,1, CV_RGB(255,0,0), 2);
                                                ^
/home/leon/mono-vo/src/visodo.cpp:194:68: error: ‘CV_FILLED’ was not declared in this scope
     rectangle( traj, Point(10, 30), Point(550, 50), CV_RGB(0,0,0), CV_FILLED);
                                                                    ^
make[2]: *** [CMakeFiles/vo.dir/src/visodo.cpp.o] error 1
make[1]: *** [CMakeFiles/vo.dir/all] error 2
make: *** [all] error 2

**Comment by avisingh599** [comment]
Are you using OpenCV 3.0?

**Comment by zyffse** [comment]
Yes, I am using OpenCV3.0.0.Here is the version information:

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import cv2
> > > print cv2.**version**
> > > 3.0.0-alpha

**Comment by avisingh599** [comment]
These kinds of errors usually happened in OpenCV across versions, I don't have opencv installed on my system any more so I cannot test. I would suggest searching in the opencv forums (or asking a question) to resolve this. 

Thanks,
Avi

**Comment by zyffse** [comment]
Thank you very much
